My Application: Item Class Reference
Item Class Reference abstract
Item is an inheritance to GameObject. Item Class is used to initialise durability to the child (Outfit and Weapon). It has a virtual void function that doesnt carry out a function but its there so its inheritance can override it.
#include <Item.h>
Public Member Functions
Item (const std::string &, const int &)
Initialises Outfit and Weapon with this constructor, name and durability.
virtual ~Item ()
Destructor for Item.
virtual void receiveDamage (const int &)=0
const int getDurability ()
Returns durability of Item.
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Count is decremented when delete is called.
std::string getName ()
Returns name of GameObject.
Protected Attributes
int durability_
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Returns count_.
Protected Member Functions inherited from GameObject
GameObject (const std::string &)
Initialises GameObject with name and adds count_.
Detailed Description
Item is an inheritance to GameObject. Item Class is used to initialise durability to the child (Outfit and Weapon). It has a virtual void function that doesnt carry out a function but its there so its inheritance can override it.
Class Item:
Definition at line 20 of file Item.h.
Constructor & Destructor Documentation
Item::Item (const std::string & name, const int & durability)
Initialises Outfit and Weapon with this constructor, name and durability.
Parameters
Definition at line 15 of file Item.cpp.
Item::~Item () virtual
Destructor for Item.
Parameters
Definition at line 33 of file Item.cpp.
Member Function Documentation
const int Item::getDurability ()
Returns durability of Item.
Parameters
Definition at line 50 of file Item.cpp.
References durability_.
Referenced by Dweller::assignOutfit(), Dweller::assignWeapon(), Dweller::getAttackDmg(), and Dweller::getSPECIAL().
virtual void Item::receiveDamage (const int &) pure virtual
Implemented in Outfit, and Weapon.
Field Documentation
int Item::durability_ protected
Definition at line 23 of file Item.h.
Referenced by getDurability(), Weapon::receiveDamage(), and Outfit::receiveDamage().
The documentation for this class was generated from the following files:
Assignment01Data/Item.h
Assignment01Data/Item.cpp